# Generated by Django 5.1.1 on 2024-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('baking', 'Baking'), ('baked', 'Baked'), ('delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image_url',
            field=models.URLField(max_length=1150),
        ),
    ]
